version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: lms-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: lms
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - lms-network

  # LMS Application
  lms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://admin:password@mongodb:27017/lms?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - FRONTEND_URL=http://localhost:5000
      - OLLAMA_MODEL=llama3.2:1b
      - MOCK_MODE=false
    depends_on:
      - mongodb
    networks:
      - lms-network

volumes:
  mongodb_data:

networks:
  lms-network:
    driver: bridge 